name: liquor_brooze_user
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  provider: ^6.1.2
  http: ^1.2.2
  get_it: ^8.0.3
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  multi_select_flutter: ^4.1.3
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.4
  marquee: ^2.3.0
  cached_network_image: ^3.4.1
  badges: ^3.1.2

dependency_overrides:
  path: 1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/app_logo/

  fonts:
    - family: Monserat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
